<a href="https://colab.research.google.com/github/kayal466/task-7/blob/main/Copy_of_DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 
 #Data.csv

**Step 1: Importing the libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt




**Step 2: Importing dataset**

In [ ]:
df = pd.read_csv('/content/Data.csv')

In [ ]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


**Step 3: Handling the missing data**

In [ ]:
df.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [ ]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
x = df.iloc[:,0:3].values
y = df.iloc[:,3:4].values

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values=np.nan,strategy = 'mean')

In [ ]:
  df1 = df.fillna (value = df['Age'].mean ())


In [ ]:
df1

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000     38.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
 df2 = df.fillna (value = df['Salary'].mean ())


In [ ]:
df2

Country           Age        Salary Purchased
0   France     44.000000  72000.000000        No
1    Spain     27.000000  48000.000000       Yes
2  Germany     30.000000  54000.000000        No
3    Spain     38.000000  61000.000000        No
4  Germany     40.000000  63777.777778       Yes
5   France     35.000000  58000.000000       Yes
6    Spain  63777.777778  52000.000000        No
7   France     48.000000  79000.000000       Yes
8  Germany     50.000000  83000.000000        No
9   France     37.000000  67000.000000       Yes

**Step** **4** : **Encoding** **a** **categorical** **data**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
Lable_x = LabelEncoder()
x[:,0] = Lable_x.fit_transform(x[:,0]) 
x = x[:,1:]

In [ ]:
x

array([[72000.0],
       [48000.0],
       [54000.0],
       [61000.0],
       [nan],
       [58000.0],
       [52000.0],
       [79000.0],
       [83000.0],
       [67000.0]], dtype=object)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
df = asarray([['Country'],['Age'],['Salary']])
print(df)
Encoder = OneHotEncoder(sparse = False)
OneHot = Encoder.fit_transform(df)
print(OneHot)

[['Country']
 ['Age']
 ['Salary']]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


**Step 5: Creating a dummy variable**

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Data.csv')
pd.get_dummies (df.['Salary'])
 


SyntaxError: ignored

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
from sklearn.model_selection import train_test_split
xtrain , xtest, ytrain,  ytest = train_test_split(x,y,test_size = .20, random_state =0)

In [ ]:
x

array([[72000.0],
       [48000.0],
       [54000.0],
       [61000.0],
       [nan],
       [58000.0],
       [52000.0],
       [79000.0],
       [83000.0],
       [67000.0]], dtype=object)

In [ ]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
Sc_x = StandardScaler()
xtrain = Sc_x.fit_transform(xtrain)
xtest = Sc_x.fit_transform(xtest)

In [ ]:
xtrain

array([[        nan],
       [ 0.44897083],
       [-1.41706417],
       [-1.0242147 ],
       [ 1.62751925],
       [-0.14030338],
       [ 0.94003267],
       [-0.43494049]])

In [ ]:
xtest

array([[-1.],
       [ 1.]])